/**
 * Decision Framework Types
 * 
 * This file defines types for the decision-making framework that helps users
 * work through complex choices with guided reflections and analysis.
 */

// The main decision to be analyzed
export interface Decision {
  id: string;
  title: string;
  description: string;
  category: string;
  stakeholders: string[];
  createdAt: number;
  updatedAt: number;
  status: DecisionStatus;
  deadline?: number;
  outcome?: string;
  confidence?: number;
}

// Status of a decision in the decision-making process
export type DecisionStatus = 
  | 'draft'        // Initial creation
  | 'analysis'     // Gathering pros/cons and insights
  | 'reflection'   // Reflecting on implications
  | 'evaluation'   // Evaluating options
  | 'decided'      // Decision made
  | 'implemented'  // Decision implemented
  | 'reviewed';    // Post-decision review

// An option being considered for a decision
export interface DecisionOption {
  id: string;
  decisionId: string;
  title: string;
  description: string;
  isRecommended?: boolean;
  score?: number;
  pros: ProCon[];
  cons: ProCon[];
  createdAt: number;
  updatedAt: number;
}

// A pro or con for an option
export interface ProCon {
  id: string;
  content: string;
  weight: number; // 1-10, how important is this factor
  category: ProConCategory;
  createdAt: number;
}

// Categories for pros and cons
export type ProConCategory = 
  | 'financial'
  | 'social'
  | 'personal'
  | 'professional'
  | 'health'
  | 'time'
  | 'ethics'
  | 'environmental'
  | 'technical'
  | 'emotional'
  | 'other';

// A guided reflection prompt to help with the decision
export interface GuidedReflection {
  id: string;
  decisionId: string;
  prompt: string;
  response: string;
  createdAt: number;
  updatedAt: number;
}

// An insight generated by AI about the decision
export interface DecisionInsight {
  id: string;
  decisionId: string;
  content: string;
  type: InsightType;
  createdAt: number;
}

// Types of AI-generated insights
export type InsightType = 
  | 'pattern'      // Pattern recognition
  | 'perspective'  // Alternative perspective
  | 'blind_spot'   // Something being overlooked
  | 'synthesis'    // Synthesis of various factors
  | 'suggestion'   // Suggested action or approach
  | 'risk'         // Potential risk identification
  | 'opportunity'  // Potential opportunity identification
  | 'clarification'; // Clarification of an ambiguous point

// A framework to structure the decision analysis
export interface DecisionFramework {
  id: string;
  name: string;
  description: string;
  steps: DecisionFrameworkStep[];
  createdAt: number;
}

// A step in a decision framework
export interface DecisionFrameworkStep {
  id: string;
  frameworkId: string;
  title: string;
  description: string;
  order: number;
  reflectionPrompts: string[];
}