import { Request, Response } from 'express';
import OpenAI from 'openai';
import path from 'path';
import fs from 'fs';
import { apiQuotaManager } from './api-quota-manager';

// OpenAI client initialization
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// The newest OpenAI model is "gpt-4o" which was released May 13, 2024. Do not change this unless explicitly requested by the user
const AI_MODEL = "gpt-4o";

/**
 * Handle content generation requests
 */
export async function generateContent(req: Request, res: Response) {
  try {
    const { prompt, style, complexity, environmentType, format } = req.body;
    
    if (!prompt) {
      return res.status(400).json({
        success: false,
        error: 'Prompt is required'
      });
    }
    
    // Check API rate limits
    const rateLimitInfo = apiQuotaManager.checkRateLimit('openai', 500);
    if (rateLimitInfo.isLimited) {
      return res.status(429).json({
        success: false,
        error: `API rate limit reached. Try again later. Reset at: ${new Date(rateLimitInfo.resetTime).toLocaleString()}`,
        meta: { resetTime: rateLimitInfo.resetTime }
      });
    }
    
    // Construct a detailed prompt for the AI
    const systemPrompt = `You are an expert 3D modeling and design AI assistant, specialized in generating detailed 3D models and scenes through text descriptions. 
Given a text prompt, generate a JSON object representing a 3D model with the following structure:
{
  "objects": [
    {
      "object": {
        "id": "unique-id",
        "type": "model",
        "name": "Descriptive name based on prompt",
        "position": [x, y, z],
        "rotation": [x, y, z],
        "scale": [x, y, z],
        "properties": {
          "color": "#hexcolor",
          "material": "material-type",
          "textures": ["list-of-textures"],
          "complexity": number,
          "vertices": estimated-number-of-vertices
        }
      },
      "previewUrl": "url-to-preview-image",
      "modelUrl": "url-to-3d-model",
      "suggestions": ["list", "of", "suggestions", "for", "improvement"],
      "metadata": {
        "generationTime": seconds-taken,
        "complexity": 1-10,
        "vertexCount": estimated-number,
        "polygonCount": estimated-number
      }
    }
  ],
  "sceneContext": {
    "lighting": "description of optimal lighting",
    "environment": "suggested environment",
    "mood": "artistic mood of the scene"
  },
  "nextSteps": ["suggested", "next", "steps"]
}

Apply the following style: ${style || 'realistic'}
Apply complexity level: ${complexity || 5}/10
Environment type: ${environmentType || 'neutral'}
`;

    // Call OpenAI API
    const completion = await openai.chat.completions.create({
      model: AI_MODEL,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: prompt }
      ],
      temperature: 0.7,
      response_format: { type: "json_object" },
    });
    
    // Record API usage
    apiQuotaManager.recordApiUsage('openai', completion.usage?.total_tokens || 0);
    
    // Parse the response
    const responseText = completion.choices[0].message.content || '{}';
    const responseData = JSON.parse(responseText);
    
    // For demonstration purposes, we'll generate a mock preview image URL
    // In a real implementation, this would be generated by an image generation API
    if (responseData.objects && responseData.objects.length > 0) {
      responseData.objects.forEach((obj: any) => {
        // Just a placeholder URL - in a real implementation, this would be a real image URL
        obj.previewUrl = `/api/immersive-authoring/static/mockpreview-${Math.floor(Math.random() * 5) + 1}.jpg`;
      });
    }
    
    return res.json({
      success: true,
      data: responseData
    });
    
  } catch (error) {
    console.error('Error in generate content:', error);
    return res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    });
  }
}

/**
 * Process natural language commands to modify 3D objects
 */
export async function processCommand(req: Request, res: Response) {
  try {
    const { command, objectId, parameters } = req.body;
    
    if (!command) {
      return res.status(400).json({
        success: false,
        error: 'Command is required'
      });
    }
    
    // Check API rate limits
    const rateLimitInfo = apiQuotaManager.checkRateLimit('openai', 300);
    if (rateLimitInfo.isLimited) {
      return res.status(429).json({
        success: false,
        error: `API rate limit reached. Try again later. Reset at: ${new Date(rateLimitInfo.resetTime).toLocaleString()}`,
        meta: { resetTime: rateLimitInfo.resetTime }
      });
    }
    
    // Construct a detailed prompt for the AI
    const systemPrompt = `You are an expert 3D modeling AI assistant that interprets natural language commands to modify 3D objects.
Given a command like "move the chair up", "rotate the lamp 45 degrees", or "make the table larger", 
parse this into a structured modification request.

Return a JSON object with the following structure:
{
  "success": true/false,
  "message": "Human-readable explanation of what was done",
  "modifications": [
    {
      "objectId": "${objectId || 'object-id'}",
      "property": "position/rotation/scale/color/etc",
      "oldValue": [old values if applicable],
      "newValue": [new values]
    }
  ]
}

If the command is vague or impossible to interpret, return:
{
  "success": false,
  "message": "Explanation of why the command couldn't be processed"
}
`;

    // Call OpenAI API
    const completion = await openai.chat.completions.create({
      model: AI_MODEL,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: command }
      ],
      temperature: 0.3,
      response_format: { type: "json_object" },
    });
    
    // Record API usage
    apiQuotaManager.recordApiUsage('openai', completion.usage?.total_tokens || 0);
    
    // Parse the response
    const responseText = completion.choices[0].message.content || '{}';
    const responseData = JSON.parse(responseText);
    
    return res.json({
      success: true,
      data: responseData
    });
    
  } catch (error) {
    console.error('Error in process command:', error);
    return res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    });
  }
}

/**
 * Provide AI assistance and suggestions for the current scene
 */
export async function getAssistance(req: Request, res: Response) {
  try {
    const { scene, question } = req.body;
    
    if (!scene || !Array.isArray(scene)) {
      return res.status(400).json({
        success: false,
        error: 'Scene data is required and must be an array'
      });
    }
    
    // Check API rate limits
    const rateLimitInfo = apiQuotaManager.checkRateLimit('openai', 350);
    if (rateLimitInfo.isLimited) {
      return res.status(429).json({
        success: false,
        error: `API rate limit reached. Try again later. Reset at: ${new Date(rateLimitInfo.resetTime).toLocaleString()}`,
        meta: { resetTime: rateLimitInfo.resetTime }
      });
    }
    
    // Construct a detailed prompt for the AI
    const systemPrompt = `You are an expert 3D modeling and design AI assistant that analyzes 3D scenes and provides helpful suggestions.
Given a 3D scene representation and optionally a specific question, analyze the scene and provide insights and suggestions.

Return a JSON object with the following structure:
{
  "suggestions": [
    "List of actionable suggestions to improve the scene"
  ],
  "analysis": {
    "composition": "Analysis of the scene composition",
    "lighting": "Analysis of the scene lighting",
    "balance": "Analysis of the visual balance",
    "complexity": numerical_value_1_to_10,
    "consistency": numerical_value_1_to_10,
    "gaps": ["list of elements", "that could be added"]
  }
}

${question ? `The user has specifically asked: "${question}". Focus your analysis on this question.` : ''}
`;

    // Call OpenAI API
    const completion = await openai.chat.completions.create({
      model: AI_MODEL,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: JSON.stringify(scene) }
      ],
      temperature: 0.5,
      response_format: { type: "json_object" },
    });
    
    // Record API usage
    apiQuotaManager.recordApiUsage('openai', completion.usage?.total_tokens || 0);
    
    // Parse the response
    const responseText = completion.choices[0].message.content || '{}';
    const responseData = JSON.parse(responseText);
    
    return res.json({
      success: true,
      data: responseData
    });
    
  } catch (error) {
    console.error('Error in get assistance:', error);
    return res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    });
  }
}

/**
 * Convert speech to text for voice commands
 */
export async function speechToText(req: Request, res: Response) {
  try {
    // Check if audio file is provided
    if (!req.files || !req.files.audio) {
      return res.status(400).json({
        success: false,
        error: 'Audio file is required'
      });
    }
    
    // Check API rate limits
    const rateLimitInfo = apiQuotaManager.checkRateLimit('openai', 150);
    if (rateLimitInfo.isLimited) {
      return res.status(429).json({
        success: false,
        error: `API rate limit reached. Try again later. Reset at: ${new Date(rateLimitInfo.resetTime).toLocaleString()}`,
        meta: { resetTime: rateLimitInfo.resetTime }
      });
    }
    
    const audioFile = req.files.audio;
    
    // In a real implementation, this would use OpenAI's Whisper API or similar
    // For now, we'll just return a mock response
    return res.json({
      success: true,
      data: {
        text: "Create a futuristic floating city with bio-luminescent features",
        confidence: 0.95
      }
    });
    
  } catch (error) {
    console.error('Error in speech to text:', error);
    return res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    });
  }
}

/**
 * Generate a preview image of the proposed 3D model
 */
export async function generatePreview(req: Request, res: Response) {
  try {
    const { prompt } = req.body;
    
    if (!prompt) {
      return res.status(400).json({
        success: false,
        error: 'Prompt is required'
      });
    }
    
    // Check API rate limits - use openai for DALL-E
    const rateLimitInfo = apiQuotaManager.checkRateLimit('openai', 200);
    if (rateLimitInfo.isLimited) {
      return res.status(429).json({
        success: false,
        error: `API rate limit reached. Try again later. Reset at: ${new Date(rateLimitInfo.resetTime).toLocaleString()}`,
        meta: { resetTime: rateLimitInfo.resetTime }
      });
    }
    
    // In a real implementation, this would call DALL-E 3 or similar
    // For now, we'll just return a mock preview
    const mockPreviews = [
      "/preview/mockpreview-1.jpg",
      "/preview/mockpreview-2.jpg",
      "/preview/mockpreview-3.jpg",
      "/preview/mockpreview-4.jpg",
      "/preview/mockpreview-5.jpg"
    ];
    
    const randomPreview = mockPreviews[Math.floor(Math.random() * mockPreviews.length)];
    
    return res.json({
      success: true,
      data: {
        previewUrl: randomPreview
      }
    });
    
  } catch (error) {
    console.error('Error in generate preview:', error);
    return res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    });
  }
}

/**
 * Serve static mock preview images (for development only)
 */
export function serveStaticMockPreview(req: Request, res: Response) {
  const previewId = req.params.id;
  const mockImagePath = path.join(__dirname, '../public/mockpreviews', previewId);
  
  // Check if the file exists
  if (fs.existsSync(mockImagePath)) {
    return res.sendFile(mockImagePath);
  }
  
  // Otherwise return a placeholder
  return res.sendFile(path.join(__dirname, '../public/mockpreviews/placeholder.jpg'));
}